server:
  port: 9045
#  servlet:
#    context-path: /demo
#连接本地数据库
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?characterEncoding=latin1&useConfigs=maxPerformance
    username: root
    password: ...mysql.
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:db/schema.sql
    initialization-mode: ALWAYS

  quartz:
    # 参见 org.springframework.boot.autoconfigure.quartz.QuartzProperties
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    scheduler-name: SpringBootDemoScheduler
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      org.quartz.jobStore.misfireThreshold: 5000
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      # 在调度流程的第一步，也就是拉取待即将触发的triggers时，是上锁的状态，即不会同时存在多个线程拉取到相同的trigger的情况，也就避免的重复调度的危险。参考：https://segmentfault.com/a/1190000015492260
      org.quartz.jobStore.acquireTriggersWithinLock: true


mybatis:
  mapper-locations: classpath:mapper/*.xml